---

- name: Docker-py | Install deps
  apt: name={{ item }}
  with_items:
    - python-pip
  tags: docker-py

- name: Docker-py | Install pip
  pip: name={{ item }} extra_args="--upgrade"
  with_items:
    - pip
    - virtualenv
  tags: docker-py

- name: Docker-py | Install package
  pip: name=docker-py version=1.1.0
  tags: docker-py