---

- name: Docker | Test apt repo
  stat: path=/etc/apt/sources.list.d/docker.list
  register: aptdockerrepo_present
  tags: apt

- name: Docker | Add apt repo
  apt_repository:
    repo='deb https://apt.dockerproject.org/repo {{ os_distribution }} main'
    state=present
  when: aptdockerrepo_present.stat.exists == false
  tags: apt

- name: Docker | Add apt repository key
  apt_key:
    id: "2C52609D"
    url: "https://apt.dockerproject.org/gpg"
    state: present
  when: aptdockerrepo_present.stat.exists == false
  tags: apt

- name: Docker | Install docker package
  apt:
    name="docker-engine={{ dockerengine_version }}~{{ os_distribution_codename }}"
    force=yes state=present
  notify: start docker
  tags: docker-engine

- name: Docker | Add user to the docker groups
  user: name="{{ ansible_ssh_user }}" groups=docker

- name: Docker | Start service
  service: name=docker state=started